version: '2'

services:
  web:
    image: restless/web
    environment:
      - serviceAUrl=http://servicea.api
      - serviceBUrl=http://serviceb.api
    ports:
      - "5000:80"
    depends_on:
      - servicea.api
      - serviceb.api

  servicea.api:
    image: restless/servicea
    expose:
      - "80"
    ports:
      - "5001:80"

  serviceb.api:
    image: restless/serviceb
    expose:
      - "80"
    ports:
      - "5002:80"